import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
	},
	backgroundColor: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: '#3F713B', // Color de fondo con transparencia
	},
	background: {
		flex: 1,
	},
	container: {
		flex: 1,
		alignItems: 'center',
	},
	logoContainer: {
		paddingTop: '10%',
		height: '30%',
		alignItems: 'center',
		justifyContent: 'center',
	},
	logo: {
		width: 300,
		height: 300,
	},
	buttonContainer: {
		flex: 8,
		width: '80%',
		height: '100%',
		alignItems: 'center',
	},
	primaryButton: {
		borderRadius: 24,
		height: 48,
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'row',
		backgroundColor: '#FFF172',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.5,
		shadowRadius: 4,
		elevation: 10,
		marginVertical: 36,
	},
	primaryButtonText: {
		fontSize: 18,
		color: '#032000',
		fontFamily: 'Montserrat-Regular',
	},
	secondaryButton: {
		borderColor: '#FFFFFF',
		borderWidth: 1,
		borderRadius: 24,
		height: 48,
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'row',
		backgroundColor: '#3F713B',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.5,
		shadowRadius: 4,
		elevation: 5,
	},
	secondaryButtonLogo: {
		position: 'relative',
		width: 16,
		height: 16,
	},
	secondaryButtonText: {
		fontSize: 16,
		color: 'white',
		fontFamily: 'Montserrat-Regular',
	},
	buttonWithLogoContainer: {
		borderRadius: 24,
		height: 48,
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'row',
		backgroundColor: '#3F713B',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.5,
		shadowRadius: 4,
		elevation: 5,
	},
	buttonWithLogoImage: {
		width: '100%',
		height: '100%',
	},
	buttonWithLogoText: {
		fontSize: 16,
		color: 'white',
		fontFamily: 'Montserrat-Regular',
	},
	separatorContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		width: '100%',
		marginVertical: 30,
	},
	separatorLine: {
		flex: 1,
		height: 1,
		backgroundColor: 'white',
	},
	separatorCircle: {
		width: 10,
		height: 10,
		borderRadius: 5,
		marginHorizontal: 10,
		borderColor: 'white',
		borderWidth: 1,
	},
	inputButton: {
		paddingHorizontal: 15,
		borderColor: '#FFFFFF',
		color: '#FFFFFF',
		borderWidth: 1,
		borderRadius: 12,
		height: 48,
		width: '100%',
		marginVertical: 10,
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'row',
		fontSize: 16,
		fontFamily: 'Montserrat-Regular',
		backgroundColor: '#3F713B',
	},
	passwordContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		width: '100%',
	},
	hidePasswordButton: {
		position: 'absolute',
		backgroundColor: 'transparent',
		right: 10,
	},
	hidePasswordButtonIcon: {
		width: 20,
		margin: 5,
	},
	forgotPasswordButton: {
		marginRight: 'auto',
	},
	forgotPasswordText: {
		color: '#FFFFFF',
		fontSize: 12,
		textAlign: 'left',
		backgroundColor: '#3F713B',
		textDecorationLine: 'underline',
		fontFamily: 'Montserrat-Regular',
	},
	bottomContainer: {
		flex: 2,
		justifyContent: 'center',
	},
	registerContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
	},
	registerText: {
		color: '#FFFFFF',
		fontSize: 18,
		textAlign: 'center',
		backgroundColor: '#3F713B',
		fontFamily: 'Montserrat-Regular',
	},
	registerButtonText: {
		color: '#FFF172',
		fontSize: 18,
		textAlign: 'center',
		backgroundColor: '#3F713B',
		textDecorationLine: 'underline',
		fontFamily: 'Montserrat-Regular',
	},
	privacyContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		width: '100%',
	},
	privacyText: {
		color: '#FFFFFF',
		fontSize: 10,
		textAlign: 'center',
		fontFamily: 'Montserrat-Regular',
	},
	privacyButtonText: {
		color: '#FFFFFF',
		fontSize: 10,
		textAlign: 'center',
		textDecorationLine: 'underline',
		fontFamily: 'Montserrat-SemiBold',
	},
	companyContainer: {
		alignItems: 'center',
		marginVertical: 10,
	},
	companyText: {
		color: '#FFFFFF',
		fontSize: 12,
		backgroundColor: '#3F713B',
		fontFamily: 'Montserrat-SemiBold',
	},
	passwordRecoveryTextContainer: {
		width: '100%',
	},
	passwordRecoveryTitle: {
		color: 'white',
		fontFamily: 'Montserrat-SemiBold',
		fontSize: 20,
		justifyContent: 'flex-start',
		marginBottom: 10,
	},
	passwordRecoveryText: {
		color: 'white',
		fontFamily: 'Montserrat-Regular',
		fontSize: 14,
	},
	resendCodeButtonContainer: { height: 36, width: '100%', marginBottom: 10 },
	resendButton: {
		borderColor: '#FFFFFF',
		borderWidth: 1,
		borderRadius: 16,
		height: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'row',
		backgroundColor: '#3F713B',
		width: '35%',
		position: 'absolute',
		right: 0,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.5,
		shadowRadius: 4,
		elevation: 10,
	},
	codeResentText: {
		color: 'white',
		fontSize: 14,
		fontFamily: 'Montserrat-SemiBold',
		textAlign: 'center',
	},
});
